select distinct ?d1 ?d2 
where {
 ?d1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/class/yago/Antibody115027189>.
?d2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://dbpedia.org/class/yago/MonoclonalAntibody115029781>.
 ?d1 <http://dbpedia.org/ontology/atcPrefix> ?o.
?d2 <http://dbpedia.org/ontology/atcPrefix> ?o.
 OPTIONAL {
 ?d1 <http://dbpedia.org/property/unii> ?u1.
 ?d1 <http://dbpedia.org/property/stdinchikey> ?s1.
 ?d1 <http://dbpedia.org/property/smiles> ?sm1.
 ?d1 <http://dbpedia.org/property/pubchem> ?pu1.
 ?d1 <http://dbpedia.org/property/molecularWeight> ?m1.
 ?d1 <http://dbpedia.org/property/kegg> ?k1.
 ?d1 <http://dbpedia.org/property/excretion> ?e1.
 ?d1 <http://dbpedia.org/property/drugbank> ?dg1. 
}.
 OPTIONAL {
?d2 <http://dbpedia.org/property/unii> ?u2.
 ?d2 <http://dbpedia.org/property/stdinchikey> ?s2.
 ?d2 <http://dbpedia.org/property/smiles> ?sm2.
 ?d2 <http://dbpedia.org/property/pubchem> ?pu2.
 ?d2 <http://dbpedia.org/property/molecularWeight> ?m2.
 ?d2 <http://dbpedia.org/property/kegg> ?k2.
 ?d2 <http://dbpedia.org/property/excretion> ?e2.
 ?d2 <http://dbpedia.org/property/drugbank> ?dg2.
}
}
                
