select distinct ?o
where {
?d1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/class/yago/Antibody115027189>.
?d2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <http://dbpedia.org/class/yago/MonoclonalAntibody115029781>.
?d1 <http://dbpedia.org/ontology/atcPrefix> ?o.
?d2 <http://dbpedia.org/ontology/atcPrefix> ?o.
 ?d1 <http://dbpedia.org/ontology/casNumber> ?p1.
 ?d1 <http://dbpedia.org/property/chemspiderid> ?sm1.
 ?d1 <http://dbpedia.org/property/target> ?k1.
 ?d2 <http://dbpedia.org/ontology/casNumber> ?p2.
 ?d2 <http://dbpedia.org/property/chemspiderid> ?sm2.
 ?d2 <http://dbpedia.org/property/target> ?k2.
}

