select distinct ?d1 
where {
?d1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/class/yago/Antibody115027189>.
 ?d1 <http://dbpedia.org/property/routesOfAdministration> ?o.
 ?d1 <http://dbpedia.org/ontology/atcPrefix> ?c1.
?d1 <http://dbpedia.org/ontology/atcSuffix> ?p1.
?d1 <http://dbpedia.org/ontology/atcSupplemental> ?u1.
?d1 <http://dbpedia.org/ontology/casNumber> ?s1.
?d1 <http://dbpedia.org/ontology/drugbank> ?sm1.
?d1 <http://dbpedia.org/ontology/wikiPageID> ?pu1.
?d1 <http://dbpedia.org/ontology/wikiPageRevisionID> ?m1.
}
                
