select distinct * where {
?d1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://umbel.org/umbel/rc/AilmentCondition>.
?d2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/Disease>.
?d1 <http://dbpedia.org/property/emedicinetopic> ?o.
?d2 <http://dbpedia.org/property/emedicinetopic> ?o.
}