select distinct *
where {
?p <http://dbpedia.org/property/currentMembers> <http://dbpedia.org/resource/Gustavo_Dudamel>.
?p <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> ?t1. 
?p <http://www.w3.org/2002/07/owl#sameAs> ?as1.
?p <http://purl.org/dc/terms/subject> ?ss1.
?p <http://dbpedia.org/ontology/activeYearsStartYear> ?ac1.
?p <http://dbpedia.org/ontology/associatedBand> ?ab1.
?p <http://dbpedia.org/ontology/associatedMusicalArtist> ?ama1.
?p <http://dbpedia.org/ontology/instrument> ?ins1.
?ins1 <http://dbpedia.org/property/birthDate> ?bd1.
?ins1 <http://dbpedia.org/property/birthPlace> ?hs1.
?ins1 <http://dbpedia.org/property/placeOfBirth> ?poB1.
?ins1 <http://dbpedia.org/property/education> ?ed1.
?ins1 <http://dbpedia.org/property/spouse> ?sp1.
?ab1 <http://xmlns.com/foaf/0.1/homepage> ?hm1.
?ab1 <http://xmlns.com/foaf/0.1/isPrimaryTopicOf> ?iPt1.
?ab1 <http://www.w3.org/ns/prov#wasDerivedFrom> ?wd1.
?ab1 <http://dbpedia.org/property/hasPhotoCollection> ?yA1.
}

